package cn.carry.mapper;

import cn.carry.domain.Bid;
import cn.carry.domain.BidExample;
import org.apache.ibatis.annotations.*;

import java.util.List;

public interface BidMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bid
     *
     * @mbggenerated
     */
    int countByExample(BidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bid
     *
     * @mbggenerated
     */
    int deleteByExample(BidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bid
     *
     * @mbggenerated
     */
    @Delete({
        "delete from `bid`",
        "where `id` = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bid
     *
     * @mbggenerated
     */
    @Insert({
        "insert into `bid` (`id`, `actualRate`, ",
        "`availableAmount`, `bidrequest_id`, ",
        "`bidUser_id`, `bidTime`, ",
        "`bidRequestTitle`)",
        "values (#{id,jdbcType=BIGINT}, #{actualrate,jdbcType=DECIMAL}, ",
        "#{availableamount,jdbcType=DECIMAL}, #{bidrequestId,jdbcType=BIGINT}, ",
        "#{biduserId,jdbcType=BIGINT}, #{bidtime,jdbcType=TIMESTAMP}, ",
        "#{bidrequesttitle,jdbcType=VARCHAR})"
    })
    int insert(Bid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bid
     *
     * @mbggenerated
     */
    int insertSelective(Bid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bid
     *
     * @mbggenerated
     */
    List<Bid> selectByExample(BidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bid
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "`id`, `actualRate`, `availableAmount`, `bidrequest_id`, `bidUser_id`, `bidTime`, ",
        "`bidRequestTitle`",
        "from `bid`",
        "where `id` = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("BaseResultMap")
    Bid selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bid
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Bid record, @Param("example") BidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bid
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Bid record, @Param("example") BidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bid
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Bid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bid
     *
     * @mbggenerated
     */
    @Update({
        "update `bid`",
        "set `actualRate` = #{actualrate,jdbcType=DECIMAL},",
          "`availableAmount` = #{availableamount,jdbcType=DECIMAL},",
          "`bidrequest_id` = #{bidrequestId,jdbcType=BIGINT},",
          "`bidUser_id` = #{biduserId,jdbcType=BIGINT},",
          "`bidTime` = #{bidtime,jdbcType=TIMESTAMP},",
          "`bidRequestTitle` = #{bidrequesttitle,jdbcType=VARCHAR}",
        "where `id` = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(Bid record);
}