package cn.carry.mapper;

import cn.carry.domain.Bidrequest;
import cn.carry.domain.BidrequestExample;
import org.apache.ibatis.annotations.*;

import java.util.List;

public interface BidrequestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bidrequest
     *
     * @mbggenerated
     */
    int countByExample(BidrequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bidrequest
     *
     * @mbggenerated
     */
    int deleteByExample(BidrequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bidrequest
     *
     * @mbggenerated
     */
    @Delete({
        "delete from `bidrequest`",
        "where `id` = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bidrequest
     *
     * @mbggenerated
     */
    @Insert({
        "insert into `bidrequest` (`id`, `version`, ",
        "`bidRequestType`, `bidRequestState`, ",
        "`bidRequestAmount`, `currentRate`, ",
        "`monthes2Return`, `bidCount`, ",
        "`totalRewardAmount`, `currentSum`, ",
        "`title`, `description`, ",
        "`note`, `disableDate`, ",
        "`createuser_id`, `disableDays`, ",
        "`minBidAmount`, `applyTime`, ",
        "`publishTime`)",
        "values (#{id,jdbcType=BIGINT}, #{version,jdbcType=INTEGER}, ",
        "#{bidrequesttype,jdbcType=TINYINT}, #{bidrequeststate,jdbcType=TINYINT}, ",
        "#{bidrequestamount,jdbcType=DECIMAL}, #{currentrate,jdbcType=DECIMAL}, ",
        "#{monthes2return,jdbcType=TINYINT}, #{bidcount,jdbcType=INTEGER}, ",
        "#{totalrewardamount,jdbcType=DECIMAL}, #{currentsum,jdbcType=DECIMAL}, ",
        "#{title,jdbcType=VARCHAR}, #{description,jdbcType=VARCHAR}, ",
        "#{note,jdbcType=VARCHAR}, #{disabledate,jdbcType=TIMESTAMP}, ",
        "#{createuserId,jdbcType=BIGINT}, #{disabledays,jdbcType=TINYINT}, ",
        "#{minbidamount,jdbcType=DECIMAL}, #{applytime,jdbcType=TIMESTAMP}, ",
        "#{publishtime,jdbcType=TIMESTAMP})"
    })
    int insert(Bidrequest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bidrequest
     *
     * @mbggenerated
     */
    int insertSelective(Bidrequest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bidrequest
     *
     * @mbggenerated
     */
    List<Bidrequest> selectByExample(BidrequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bidrequest
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "`id`, `version`, `bidRequestType`, `bidRequestState`, `bidRequestAmount`, `currentRate`, ",
        "`monthes2Return`, `bidCount`, `totalRewardAmount`, `currentSum`, `title`, `description`, ",
        "`note`, `disableDate`, `createuser_id`, `disableDays`, `minBidAmount`, `applyTime`, ",
        "`publishTime`",
        "from `bidrequest`",
        "where `id` = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("BaseResultMap")
    Bidrequest selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bidrequest
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Bidrequest record, @Param("example") BidrequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bidrequest
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Bidrequest record, @Param("example") BidrequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bidrequest
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Bidrequest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bidrequest
     *
     * @mbggenerated
     */
    @Update({
        "update `bidrequest`",
        "set `version` = #{version,jdbcType=INTEGER},",
          "`bidRequestType` = #{bidrequesttype,jdbcType=TINYINT},",
          "`bidRequestState` = #{bidrequeststate,jdbcType=TINYINT},",
          "`bidRequestAmount` = #{bidrequestamount,jdbcType=DECIMAL},",
          "`currentRate` = #{currentrate,jdbcType=DECIMAL},",
          "`monthes2Return` = #{monthes2return,jdbcType=TINYINT},",
          "`bidCount` = #{bidcount,jdbcType=INTEGER},",
          "`totalRewardAmount` = #{totalrewardamount,jdbcType=DECIMAL},",
          "`currentSum` = #{currentsum,jdbcType=DECIMAL},",
          "`title` = #{title,jdbcType=VARCHAR},",
          "`description` = #{description,jdbcType=VARCHAR},",
          "`note` = #{note,jdbcType=VARCHAR},",
          "`disableDate` = #{disabledate,jdbcType=TIMESTAMP},",
          "`createuser_id` = #{createuserId,jdbcType=BIGINT},",
          "`disableDays` = #{disabledays,jdbcType=TINYINT},",
          "`minBidAmount` = #{minbidamount,jdbcType=DECIMAL},",
          "`applyTime` = #{applytime,jdbcType=TIMESTAMP},",
          "`publishTime` = #{publishtime,jdbcType=TIMESTAMP}",
        "where `id` = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(Bidrequest record);
}