package cn.carry.mapper;

import cn.carry.domain.Bidrequestaudithistory;
import cn.carry.domain.BidrequestaudithistoryExample;
import org.apache.ibatis.annotations.*;

import java.util.List;

public interface BidrequestaudithistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bidrequestaudithistory
     *
     * @mbggenerated
     */
    int countByExample(BidrequestaudithistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bidrequestaudithistory
     *
     * @mbggenerated
     */
    int deleteByExample(BidrequestaudithistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bidrequestaudithistory
     *
     * @mbggenerated
     */
    @Delete({
        "delete from `bidrequestaudithistory`",
        "where `id` = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bidrequestaudithistory
     *
     * @mbggenerated
     */
    @Insert({
        "insert into `bidrequestaudithistory` (`id`, `state`, ",
        "`remark`, `auditTime`, ",
        "`applyTime`, `auditor_id`, ",
        "`applier_id`, `bidRequestId`, ",
        "`auditType`)",
        "values (#{id,jdbcType=BIGINT}, #{state,jdbcType=TINYINT}, ",
        "#{remark,jdbcType=VARCHAR}, #{audittime,jdbcType=TIMESTAMP}, ",
        "#{applytime,jdbcType=TIMESTAMP}, #{auditorId,jdbcType=BIGINT}, ",
        "#{applierId,jdbcType=BIGINT}, #{bidrequestid,jdbcType=BIGINT}, ",
        "#{audittype,jdbcType=TINYINT})"
    })
    int insert(Bidrequestaudithistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bidrequestaudithistory
     *
     * @mbggenerated
     */
    int insertSelective(Bidrequestaudithistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bidrequestaudithistory
     *
     * @mbggenerated
     */
    List<Bidrequestaudithistory> selectByExample(BidrequestaudithistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bidrequestaudithistory
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "`id`, `state`, `remark`, `auditTime`, `applyTime`, `auditor_id`, `applier_id`, ",
        "`bidRequestId`, `auditType`",
        "from `bidrequestaudithistory`",
        "where `id` = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("BaseResultMap")
    Bidrequestaudithistory selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bidrequestaudithistory
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Bidrequestaudithistory record, @Param("example") BidrequestaudithistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bidrequestaudithistory
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Bidrequestaudithistory record, @Param("example") BidrequestaudithistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bidrequestaudithistory
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Bidrequestaudithistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bidrequestaudithistory
     *
     * @mbggenerated
     */
    @Update({
        "update `bidrequestaudithistory`",
        "set `state` = #{state,jdbcType=TINYINT},",
          "`remark` = #{remark,jdbcType=VARCHAR},",
          "`auditTime` = #{audittime,jdbcType=TIMESTAMP},",
          "`applyTime` = #{applytime,jdbcType=TIMESTAMP},",
          "`auditor_id` = #{auditorId,jdbcType=BIGINT},",
          "`applier_id` = #{applierId,jdbcType=BIGINT},",
          "`bidRequestId` = #{bidrequestid,jdbcType=BIGINT},",
          "`auditType` = #{audittype,jdbcType=TINYINT}",
        "where `id` = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(Bidrequestaudithistory record);
}