package cn.carry.mapper;

import cn.carry.domain.Iplog;
import cn.carry.domain.IplogExample;
import org.apache.ibatis.annotations.*;

import java.util.List;

public interface IplogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iplog
     *
     * @mbggenerated
     */
    int countByExample(IplogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iplog
     *
     * @mbggenerated
     */
    int deleteByExample(IplogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iplog
     *
     * @mbggenerated
     */
    @Delete({
        "delete from `iplog`",
        "where `id` = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iplog
     *
     * @mbggenerated
     */
    @Insert({
        "insert into `iplog` (`id`, `ip`, `loginState`, ",
        "`username`, `loginInfoId`, ",
        "`loginType`, `loginTime`)",
        "values (#{id,jdbcType=BIGINT}, #{ip,jdbcType=VARCHAR}, #{loginstate,jdbcType=TINYINT}, ",
        "#{username,jdbcType=VARCHAR}, #{logininfoid,jdbcType=BIGINT}, ",
        "#{logintype,jdbcType=TINYINT}, #{logintime,jdbcType=TIMESTAMP})"
    })
    int insert(Iplog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iplog
     *
     * @mbggenerated
     */
    int insertSelective(Iplog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iplog
     *
     * @mbggenerated
     */
    List<Iplog> selectByExample(IplogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iplog
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "`id`, `ip`, `loginState`, `username`, `loginInfoId`, `loginType`, `loginTime`",
        "from `iplog`",
        "where `id` = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("BaseResultMap")
    Iplog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iplog
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Iplog record, @Param("example") IplogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iplog
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Iplog record, @Param("example") IplogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iplog
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Iplog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table iplog
     *
     * @mbggenerated
     */
    @Update({
        "update `iplog`",
        "set `ip` = #{ip,jdbcType=VARCHAR},",
          "`loginState` = #{loginstate,jdbcType=TINYINT},",
          "`username` = #{username,jdbcType=VARCHAR},",
          "`loginInfoId` = #{logininfoid,jdbcType=BIGINT},",
          "`loginType` = #{logintype,jdbcType=TINYINT},",
          "`loginTime` = #{logintime,jdbcType=TIMESTAMP}",
        "where `id` = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(Iplog record);
}