package cn.carry.mapper;

import cn.carry.domain.Logininfo;
import cn.carry.domain.LogininfoExample;
import org.apache.ibatis.annotations.*;

import java.util.List;

public interface LogininfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logininfo
     *
     * @mbggenerated
     */
    int countByExample(LogininfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logininfo
     *
     * @mbggenerated
     */
    int deleteByExample(LogininfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logininfo
     *
     * @mbggenerated
     */
    @Delete({
        "delete from `logininfo`",
        "where `id` = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logininfo
     *
     * @mbggenerated
     */
    @Insert({
        "insert into `logininfo` (`id`, `username`, ",
        "`password`, `state`, ",
        "`usertype`, `admin`)",
        "values (#{id,jdbcType=BIGINT}, #{username,jdbcType=VARCHAR}, ",
        "#{password,jdbcType=VARCHAR}, #{state,jdbcType=TINYINT}, ",
        "#{usertype,jdbcType=TINYINT}, #{admin,jdbcType=BIT})"
    })
    int insert(Logininfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logininfo
     *
     * @mbggenerated
     */
    int insertSelective(Logininfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logininfo
     *
     * @mbggenerated
     */
    List<Logininfo> selectByExample(LogininfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logininfo
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "`id`, `username`, `password`, `state`, `usertype`, `admin`",
        "from `logininfo`",
        "where `id` = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("BaseResultMap")
    Logininfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logininfo
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Logininfo record, @Param("example") LogininfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logininfo
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Logininfo record, @Param("example") LogininfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logininfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Logininfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logininfo
     *
     * @mbggenerated
     */
    @Update({
        "update `logininfo`",
        "set `username` = #{username,jdbcType=VARCHAR},",
          "`password` = #{password,jdbcType=VARCHAR},",
          "`state` = #{state,jdbcType=TINYINT},",
          "`usertype` = #{usertype,jdbcType=TINYINT},",
          "`admin` = #{admin,jdbcType=BIT}",
        "where `id` = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(Logininfo record);
}