package cn.carry.mapper;

import cn.carry.domain.Paymentscheduledetail;
import cn.carry.domain.PaymentscheduledetailExample;
import org.apache.ibatis.annotations.*;

import java.util.List;

public interface PaymentscheduledetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paymentscheduledetail
     *
     * @mbggenerated
     */
    int countByExample(PaymentscheduledetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paymentscheduledetail
     *
     * @mbggenerated
     */
    int deleteByExample(PaymentscheduledetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paymentscheduledetail
     *
     * @mbggenerated
     */
    @Delete({
        "delete from `paymentscheduledetail`",
        "where `id` = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paymentscheduledetail
     *
     * @mbggenerated
     */
    @Insert({
        "insert into `paymentscheduledetail` (`id`, `bidamount`, ",
        "`bid_id`, `totalamount`, ",
        "`principal`, `interest`, ",
        "`monthindex`, `deadline`, ",
        "`bidrequest_id`, `paydate`, ",
        "`returntype`, `paymentschedule_id`, ",
        "`fromlogininfo_id`, `tologininfo_id`)",
        "values (#{id,jdbcType=BIGINT}, #{bidamount,jdbcType=DECIMAL}, ",
        "#{bidId,jdbcType=BIGINT}, #{totalamount,jdbcType=DECIMAL}, ",
        "#{principal,jdbcType=DECIMAL}, #{interest,jdbcType=DECIMAL}, ",
        "#{monthindex,jdbcType=TINYINT}, #{deadline,jdbcType=TIMESTAMP}, ",
        "#{bidrequestId,jdbcType=BIGINT}, #{paydate,jdbcType=TIMESTAMP}, ",
        "#{returntype,jdbcType=TINYINT}, #{paymentscheduleId,jdbcType=BIGINT}, ",
        "#{fromlogininfoId,jdbcType=BIGINT}, #{tologininfoId,jdbcType=BIGINT})"
    })
    int insert(Paymentscheduledetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paymentscheduledetail
     *
     * @mbggenerated
     */
    int insertSelective(Paymentscheduledetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paymentscheduledetail
     *
     * @mbggenerated
     */
    List<Paymentscheduledetail> selectByExample(PaymentscheduledetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paymentscheduledetail
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "`id`, `bidamount`, `bid_id`, `totalamount`, `principal`, `interest`, `monthindex`, ",
        "`deadline`, `bidrequest_id`, `paydate`, `returntype`, `paymentschedule_id`, ",
        "`fromlogininfo_id`, `tologininfo_id`",
        "from `paymentscheduledetail`",
        "where `id` = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("BaseResultMap")
    Paymentscheduledetail selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paymentscheduledetail
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Paymentscheduledetail record, @Param("example") PaymentscheduledetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paymentscheduledetail
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Paymentscheduledetail record, @Param("example") PaymentscheduledetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paymentscheduledetail
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Paymentscheduledetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paymentscheduledetail
     *
     * @mbggenerated
     */
    @Update({
        "update `paymentscheduledetail`",
        "set `bidamount` = #{bidamount,jdbcType=DECIMAL},",
          "`bid_id` = #{bidId,jdbcType=BIGINT},",
          "`totalamount` = #{totalamount,jdbcType=DECIMAL},",
          "`principal` = #{principal,jdbcType=DECIMAL},",
          "`interest` = #{interest,jdbcType=DECIMAL},",
          "`monthindex` = #{monthindex,jdbcType=TINYINT},",
          "`deadline` = #{deadline,jdbcType=TIMESTAMP},",
          "`bidrequest_id` = #{bidrequestId,jdbcType=BIGINT},",
          "`paydate` = #{paydate,jdbcType=TIMESTAMP},",
          "`returntype` = #{returntype,jdbcType=TINYINT},",
          "`paymentschedule_id` = #{paymentscheduleId,jdbcType=BIGINT},",
          "`fromlogininfo_id` = #{fromlogininfoId,jdbcType=BIGINT},",
          "`tologininfo_id` = #{tologininfoId,jdbcType=BIGINT}",
        "where `id` = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(Paymentscheduledetail record);
}