package cn.carry.mapper;

import cn.carry.domain.Paymentschedule;
import cn.carry.domain.PaymentscheduleExample;
import org.apache.ibatis.annotations.*;

import java.util.List;

public interface PaymentscheduleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paymentschedule
     *
     * @mbggenerated
     */
    int countByExample(PaymentscheduleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paymentschedule
     *
     * @mbggenerated
     */
    int deleteByExample(PaymentscheduleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paymentschedule
     *
     * @mbggenerated
     */
    @Delete({
        "delete from `paymentschedule`",
        "where `id` = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paymentschedule
     *
     * @mbggenerated
     */
    @Insert({
        "insert into `paymentschedule` (`id`, `deadLine`, ",
        "`payDate`, `totalAmount`, ",
        "`principal`, `interest`, ",
        "`monthIndex`, `state`, ",
        "`bidRequestType`, `returnType`, ",
        "`bidrequest_id`, `biduser_id`, ",
        "`bidRequestTitle`)",
        "values (#{id,jdbcType=BIGINT}, #{deadline,jdbcType=TIMESTAMP}, ",
        "#{paydate,jdbcType=TIMESTAMP}, #{totalamount,jdbcType=DECIMAL}, ",
        "#{principal,jdbcType=DECIMAL}, #{interest,jdbcType=DECIMAL}, ",
        "#{monthindex,jdbcType=TINYINT}, #{state,jdbcType=TINYINT}, ",
        "#{bidrequesttype,jdbcType=TINYINT}, #{returntype,jdbcType=TINYINT}, ",
        "#{bidrequestId,jdbcType=BIGINT}, #{biduserId,jdbcType=BIGINT}, ",
        "#{bidrequesttitle,jdbcType=VARCHAR})"
    })
    int insert(Paymentschedule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paymentschedule
     *
     * @mbggenerated
     */
    int insertSelective(Paymentschedule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paymentschedule
     *
     * @mbggenerated
     */
    List<Paymentschedule> selectByExample(PaymentscheduleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paymentschedule
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "`id`, `deadLine`, `payDate`, `totalAmount`, `principal`, `interest`, `monthIndex`, ",
        "`state`, `bidRequestType`, `returnType`, `bidrequest_id`, `biduser_id`, `bidRequestTitle`",
        "from `paymentschedule`",
        "where `id` = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("BaseResultMap")
    Paymentschedule selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paymentschedule
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Paymentschedule record, @Param("example") PaymentscheduleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paymentschedule
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Paymentschedule record, @Param("example") PaymentscheduleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paymentschedule
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Paymentschedule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paymentschedule
     *
     * @mbggenerated
     */
    @Update({
        "update `paymentschedule`",
        "set `deadLine` = #{deadline,jdbcType=TIMESTAMP},",
          "`payDate` = #{paydate,jdbcType=TIMESTAMP},",
          "`totalAmount` = #{totalamount,jdbcType=DECIMAL},",
          "`principal` = #{principal,jdbcType=DECIMAL},",
          "`interest` = #{interest,jdbcType=DECIMAL},",
          "`monthIndex` = #{monthindex,jdbcType=TINYINT},",
          "`state` = #{state,jdbcType=TINYINT},",
          "`bidRequestType` = #{bidrequesttype,jdbcType=TINYINT},",
          "`returnType` = #{returntype,jdbcType=TINYINT},",
          "`bidrequest_id` = #{bidrequestId,jdbcType=BIGINT},",
          "`biduser_id` = #{biduserId,jdbcType=BIGINT},",
          "`bidRequestTitle` = #{bidrequesttitle,jdbcType=VARCHAR}",
        "where `id` = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(Paymentschedule record);
}