package cn.carry.mapper;

import cn.carry.domain.Realauth;
import cn.carry.domain.RealauthExample;
import org.apache.ibatis.annotations.*;

import java.util.List;

public interface RealauthMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table realauth
     *
     * @mbggenerated
     */
    int countByExample(RealauthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table realauth
     *
     * @mbggenerated
     */
    int deleteByExample(RealauthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table realauth
     *
     * @mbggenerated
     */
    @Delete({
        "delete from `realauth`",
        "where `id` = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table realauth
     *
     * @mbggenerated
     */
    @Insert({
        "insert into `realauth` (`id`, `realname`, ",
        "`sex`, `birthDate`, ",
        "`idNumber`, `address`, ",
        "`state`, `image1`, `image2`, ",
        "`remark`, `auditTime`, ",
        "`applyTime`, `auditor_id`, ",
        "`applier_id`)",
        "values (#{id,jdbcType=BIGINT}, #{realname,jdbcType=VARCHAR}, ",
        "#{sex,jdbcType=TINYINT}, #{birthdate,jdbcType=VARCHAR}, ",
        "#{idnumber,jdbcType=VARCHAR}, #{address,jdbcType=VARCHAR}, ",
        "#{state,jdbcType=TINYINT}, #{image1,jdbcType=VARCHAR}, #{image2,jdbcType=VARCHAR}, ",
        "#{remark,jdbcType=VARCHAR}, #{audittime,jdbcType=TIMESTAMP}, ",
        "#{applytime,jdbcType=TIMESTAMP}, #{auditorId,jdbcType=BIGINT}, ",
        "#{applierId,jdbcType=BIGINT})"
    })
    int insert(Realauth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table realauth
     *
     * @mbggenerated
     */
    int insertSelective(Realauth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table realauth
     *
     * @mbggenerated
     */
    List<Realauth> selectByExample(RealauthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table realauth
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "`id`, `realname`, `sex`, `birthDate`, `idNumber`, `address`, `state`, `image1`, ",
        "`image2`, `remark`, `auditTime`, `applyTime`, `auditor_id`, `applier_id`",
        "from `realauth`",
        "where `id` = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("BaseResultMap")
    Realauth selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table realauth
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Realauth record, @Param("example") RealauthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table realauth
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Realauth record, @Param("example") RealauthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table realauth
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Realauth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table realauth
     *
     * @mbggenerated
     */
    @Update({
        "update `realauth`",
        "set `realname` = #{realname,jdbcType=VARCHAR},",
          "`sex` = #{sex,jdbcType=TINYINT},",
          "`birthDate` = #{birthdate,jdbcType=VARCHAR},",
          "`idNumber` = #{idnumber,jdbcType=VARCHAR},",
          "`address` = #{address,jdbcType=VARCHAR},",
          "`state` = #{state,jdbcType=TINYINT},",
          "`image1` = #{image1,jdbcType=VARCHAR},",
          "`image2` = #{image2,jdbcType=VARCHAR},",
          "`remark` = #{remark,jdbcType=VARCHAR},",
          "`auditTime` = #{audittime,jdbcType=TIMESTAMP},",
          "`applyTime` = #{applytime,jdbcType=TIMESTAMP},",
          "`auditor_id` = #{auditorId,jdbcType=BIGINT},",
          "`applier_id` = #{applierId,jdbcType=BIGINT}",
        "where `id` = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(Realauth record);
}