package cn.carry.mapper;

import cn.carry.domain.Systemdictionary;
import cn.carry.domain.SystemdictionaryExample;
import org.apache.ibatis.annotations.*;

import java.util.List;

public interface SystemdictionaryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemdictionary
     *
     * @mbggenerated
     */
    int countByExample(SystemdictionaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemdictionary
     *
     * @mbggenerated
     */
    int deleteByExample(SystemdictionaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemdictionary
     *
     * @mbggenerated
     */
    @Delete({
        "delete from `systemdictionary`",
        "where `id` = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemdictionary
     *
     * @mbggenerated
     */
    @Insert({
        "insert into `systemdictionary` (`id`, `sn`, `title`, ",
        "`intro`)",
        "values (#{id,jdbcType=BIGINT}, #{sn,jdbcType=VARCHAR}, #{title,jdbcType=VARCHAR}, ",
        "#{intro,jdbcType=VARCHAR})"
    })
    int insert(Systemdictionary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemdictionary
     *
     * @mbggenerated
     */
    int insertSelective(Systemdictionary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemdictionary
     *
     * @mbggenerated
     */
    List<Systemdictionary> selectByExample(SystemdictionaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemdictionary
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "`id`, `sn`, `title`, `intro`",
        "from `systemdictionary`",
        "where `id` = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("BaseResultMap")
    Systemdictionary selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemdictionary
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Systemdictionary record, @Param("example") SystemdictionaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemdictionary
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Systemdictionary record, @Param("example") SystemdictionaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemdictionary
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Systemdictionary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemdictionary
     *
     * @mbggenerated
     */
    @Update({
        "update `systemdictionary`",
        "set `sn` = #{sn,jdbcType=VARCHAR},",
          "`title` = #{title,jdbcType=VARCHAR},",
          "`intro` = #{intro,jdbcType=VARCHAR}",
        "where `id` = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(Systemdictionary record);
}