package cn.carry.mapper;

import cn.carry.domain.Systemaccount;
import cn.carry.domain.SystemaccountExample;
import org.apache.ibatis.annotations.*;

import java.util.List;

public interface SystemaccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemaccount
     *
     * @mbggenerated
     */
    int countByExample(SystemaccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemaccount
     *
     * @mbggenerated
     */
    int deleteByExample(SystemaccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemaccount
     *
     * @mbggenerated
     */
    @Delete({
        "delete from `systemaccount`",
        "where `id` = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemaccount
     *
     * @mbggenerated
     */
    @Insert({
        "insert into `systemaccount` (`id`, `version`, ",
        "`beginDate`, `endDate`, ",
        "`createdate`, `totalbalance`, ",
        "`freezedamount`)",
        "values (#{id,jdbcType=BIGINT}, #{version,jdbcType=INTEGER}, ",
        "#{begindate,jdbcType=TIMESTAMP}, #{enddate,jdbcType=TIMESTAMP}, ",
        "#{createdate,jdbcType=TIMESTAMP}, #{totalbalance,jdbcType=DECIMAL}, ",
        "#{freezedamount,jdbcType=DECIMAL})"
    })
    int insert(Systemaccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemaccount
     *
     * @mbggenerated
     */
    int insertSelective(Systemaccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemaccount
     *
     * @mbggenerated
     */
    List<Systemaccount> selectByExample(SystemaccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemaccount
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "`id`, `version`, `beginDate`, `endDate`, `createdate`, `totalbalance`, `freezedamount`",
        "from `systemaccount`",
        "where `id` = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("BaseResultMap")
    Systemaccount selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemaccount
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Systemaccount record, @Param("example") SystemaccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemaccount
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Systemaccount record, @Param("example") SystemaccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemaccount
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Systemaccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemaccount
     *
     * @mbggenerated
     */
    @Update({
        "update `systemaccount`",
        "set `version` = #{version,jdbcType=INTEGER},",
          "`beginDate` = #{begindate,jdbcType=TIMESTAMP},",
          "`endDate` = #{enddate,jdbcType=TIMESTAMP},",
          "`createdate` = #{createdate,jdbcType=TIMESTAMP},",
          "`totalbalance` = #{totalbalance,jdbcType=DECIMAL},",
          "`freezedamount` = #{freezedamount,jdbcType=DECIMAL}",
        "where `id` = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(Systemaccount record);
}