package cn.carry.mapper;

import cn.carry.domain.Vedioauth;
import cn.carry.domain.VedioauthExample;
import org.apache.ibatis.annotations.*;

import java.util.List;

public interface VedioauthMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vedioauth
     *
     * @mbggenerated
     */
    int countByExample(VedioauthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vedioauth
     *
     * @mbggenerated
     */
    int deleteByExample(VedioauthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vedioauth
     *
     * @mbggenerated
     */
    @Delete({
        "delete from `vedioauth`",
        "where `id` = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vedioauth
     *
     * @mbggenerated
     */
    @Insert({
        "insert into `vedioauth` (`id`, `state`, ",
        "`remark`, `auditTime`, ",
        "`applyTime`, `auditor_id`, ",
        "`applier_id`)",
        "values (#{id,jdbcType=BIGINT}, #{state,jdbcType=TINYINT}, ",
        "#{remark,jdbcType=VARCHAR}, #{audittime,jdbcType=TIMESTAMP}, ",
        "#{applytime,jdbcType=TIMESTAMP}, #{auditorId,jdbcType=BIGINT}, ",
        "#{applierId,jdbcType=BIGINT})"
    })
    int insert(Vedioauth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vedioauth
     *
     * @mbggenerated
     */
    int insertSelective(Vedioauth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vedioauth
     *
     * @mbggenerated
     */
    List<Vedioauth> selectByExample(VedioauthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vedioauth
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "`id`, `state`, `remark`, `auditTime`, `applyTime`, `auditor_id`, `applier_id`",
        "from `vedioauth`",
        "where `id` = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("BaseResultMap")
    Vedioauth selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vedioauth
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Vedioauth record, @Param("example") VedioauthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vedioauth
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Vedioauth record, @Param("example") VedioauthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vedioauth
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Vedioauth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vedioauth
     *
     * @mbggenerated
     */
    @Update({
        "update `vedioauth`",
        "set `state` = #{state,jdbcType=TINYINT},",
          "`remark` = #{remark,jdbcType=VARCHAR},",
          "`auditTime` = #{audittime,jdbcType=TIMESTAMP},",
          "`applyTime` = #{applytime,jdbcType=TIMESTAMP},",
          "`auditor_id` = #{auditorId,jdbcType=BIGINT},",
          "`applier_id` = #{applierId,jdbcType=BIGINT}",
        "where `id` = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(Vedioauth record);
}