package cn.carry.domain;

import java.math.BigDecimal;
import java.util.Date;

public class Accountflow {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accountflow.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accountflow.accountActionType
     *
     * @mbggenerated
     */
    private Byte accountactiontype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accountflow.amount
     *
     * @mbggenerated
     */
    private BigDecimal amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accountflow.note
     *
     * @mbggenerated
     */
    private String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accountflow.balance
     *
     * @mbggenerated
     */
    private BigDecimal balance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accountflow.freezed
     *
     * @mbggenerated
     */
    private BigDecimal freezed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accountflow.actionTime
     *
     * @mbggenerated
     */
    private Date actiontime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accountflow.account_id
     *
     * @mbggenerated
     */
    private Long accountId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accountflow.id
     *
     * @return the value of accountflow.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accountflow.id
     *
     * @param id the value for accountflow.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accountflow.accountActionType
     *
     * @return the value of accountflow.accountActionType
     *
     * @mbggenerated
     */
    public Byte getAccountactiontype() {
        return accountactiontype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accountflow.accountActionType
     *
     * @param accountactiontype the value for accountflow.accountActionType
     *
     * @mbggenerated
     */
    public void setAccountactiontype(Byte accountactiontype) {
        this.accountactiontype = accountactiontype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accountflow.amount
     *
     * @return the value of accountflow.amount
     *
     * @mbggenerated
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accountflow.amount
     *
     * @param amount the value for accountflow.amount
     *
     * @mbggenerated
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accountflow.note
     *
     * @return the value of accountflow.note
     *
     * @mbggenerated
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accountflow.note
     *
     * @param note the value for accountflow.note
     *
     * @mbggenerated
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accountflow.balance
     *
     * @return the value of accountflow.balance
     *
     * @mbggenerated
     */
    public BigDecimal getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accountflow.balance
     *
     * @param balance the value for accountflow.balance
     *
     * @mbggenerated
     */
    public void setBalance(BigDecimal balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accountflow.freezed
     *
     * @return the value of accountflow.freezed
     *
     * @mbggenerated
     */
    public BigDecimal getFreezed() {
        return freezed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accountflow.freezed
     *
     * @param freezed the value for accountflow.freezed
     *
     * @mbggenerated
     */
    public void setFreezed(BigDecimal freezed) {
        this.freezed = freezed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accountflow.actionTime
     *
     * @return the value of accountflow.actionTime
     *
     * @mbggenerated
     */
    public Date getActiontime() {
        return actiontime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accountflow.actionTime
     *
     * @param actiontime the value for accountflow.actionTime
     *
     * @mbggenerated
     */
    public void setActiontime(Date actiontime) {
        this.actiontime = actiontime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accountflow.account_id
     *
     * @return the value of accountflow.account_id
     *
     * @mbggenerated
     */
    public Long getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accountflow.account_id
     *
     * @param accountId the value for accountflow.account_id
     *
     * @mbggenerated
     */
    public void setAccountId(Long accountId) {
        this.accountId = accountId;
    }
}