package cn.carry.domain;

import java.math.BigDecimal;
import java.util.Date;

public class Bid {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bid.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bid.actualRate
     *
     * @mbggenerated
     */
    private BigDecimal actualrate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bid.availableAmount
     *
     * @mbggenerated
     */
    private BigDecimal availableamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bid.bidrequest_id
     *
     * @mbggenerated
     */
    private Long bidrequestId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bid.bidUser_id
     *
     * @mbggenerated
     */
    private Long biduserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bid.bidTime
     *
     * @mbggenerated
     */
    private Date bidtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bid.bidRequestTitle
     *
     * @mbggenerated
     */
    private String bidrequesttitle;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bid.id
     *
     * @return the value of bid.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bid.id
     *
     * @param id the value for bid.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bid.actualRate
     *
     * @return the value of bid.actualRate
     *
     * @mbggenerated
     */
    public BigDecimal getActualrate() {
        return actualrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bid.actualRate
     *
     * @param actualrate the value for bid.actualRate
     *
     * @mbggenerated
     */
    public void setActualrate(BigDecimal actualrate) {
        this.actualrate = actualrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bid.availableAmount
     *
     * @return the value of bid.availableAmount
     *
     * @mbggenerated
     */
    public BigDecimal getAvailableamount() {
        return availableamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bid.availableAmount
     *
     * @param availableamount the value for bid.availableAmount
     *
     * @mbggenerated
     */
    public void setAvailableamount(BigDecimal availableamount) {
        this.availableamount = availableamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bid.bidrequest_id
     *
     * @return the value of bid.bidrequest_id
     *
     * @mbggenerated
     */
    public Long getBidrequestId() {
        return bidrequestId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bid.bidrequest_id
     *
     * @param bidrequestId the value for bid.bidrequest_id
     *
     * @mbggenerated
     */
    public void setBidrequestId(Long bidrequestId) {
        this.bidrequestId = bidrequestId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bid.bidUser_id
     *
     * @return the value of bid.bidUser_id
     *
     * @mbggenerated
     */
    public Long getBiduserId() {
        return biduserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bid.bidUser_id
     *
     * @param biduserId the value for bid.bidUser_id
     *
     * @mbggenerated
     */
    public void setBiduserId(Long biduserId) {
        this.biduserId = biduserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bid.bidTime
     *
     * @return the value of bid.bidTime
     *
     * @mbggenerated
     */
    public Date getBidtime() {
        return bidtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bid.bidTime
     *
     * @param bidtime the value for bid.bidTime
     *
     * @mbggenerated
     */
    public void setBidtime(Date bidtime) {
        this.bidtime = bidtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bid.bidRequestTitle
     *
     * @return the value of bid.bidRequestTitle
     *
     * @mbggenerated
     */
    public String getBidrequesttitle() {
        return bidrequesttitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bid.bidRequestTitle
     *
     * @param bidrequesttitle the value for bid.bidRequestTitle
     *
     * @mbggenerated
     */
    public void setBidrequesttitle(String bidrequesttitle) {
        this.bidrequesttitle = bidrequesttitle == null ? null : bidrequesttitle.trim();
    }
}