package cn.carry.domain;

import java.util.Date;

public class Bidrequestaudithistory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bidrequestaudithistory.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bidrequestaudithistory.state
     *
     * @mbggenerated
     */
    private Byte state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bidrequestaudithistory.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bidrequestaudithistory.auditTime
     *
     * @mbggenerated
     */
    private Date audittime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bidrequestaudithistory.applyTime
     *
     * @mbggenerated
     */
    private Date applytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bidrequestaudithistory.auditor_id
     *
     * @mbggenerated
     */
    private Long auditorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bidrequestaudithistory.applier_id
     *
     * @mbggenerated
     */
    private Long applierId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bidrequestaudithistory.bidRequestId
     *
     * @mbggenerated
     */
    private Long bidrequestid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bidrequestaudithistory.auditType
     *
     * @mbggenerated
     */
    private Byte audittype;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bidrequestaudithistory.id
     *
     * @return the value of bidrequestaudithistory.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bidrequestaudithistory.id
     *
     * @param id the value for bidrequestaudithistory.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bidrequestaudithistory.state
     *
     * @return the value of bidrequestaudithistory.state
     *
     * @mbggenerated
     */
    public Byte getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bidrequestaudithistory.state
     *
     * @param state the value for bidrequestaudithistory.state
     *
     * @mbggenerated
     */
    public void setState(Byte state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bidrequestaudithistory.remark
     *
     * @return the value of bidrequestaudithistory.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bidrequestaudithistory.remark
     *
     * @param remark the value for bidrequestaudithistory.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bidrequestaudithistory.auditTime
     *
     * @return the value of bidrequestaudithistory.auditTime
     *
     * @mbggenerated
     */
    public Date getAudittime() {
        return audittime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bidrequestaudithistory.auditTime
     *
     * @param audittime the value for bidrequestaudithistory.auditTime
     *
     * @mbggenerated
     */
    public void setAudittime(Date audittime) {
        this.audittime = audittime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bidrequestaudithistory.applyTime
     *
     * @return the value of bidrequestaudithistory.applyTime
     *
     * @mbggenerated
     */
    public Date getApplytime() {
        return applytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bidrequestaudithistory.applyTime
     *
     * @param applytime the value for bidrequestaudithistory.applyTime
     *
     * @mbggenerated
     */
    public void setApplytime(Date applytime) {
        this.applytime = applytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bidrequestaudithistory.auditor_id
     *
     * @return the value of bidrequestaudithistory.auditor_id
     *
     * @mbggenerated
     */
    public Long getAuditorId() {
        return auditorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bidrequestaudithistory.auditor_id
     *
     * @param auditorId the value for bidrequestaudithistory.auditor_id
     *
     * @mbggenerated
     */
    public void setAuditorId(Long auditorId) {
        this.auditorId = auditorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bidrequestaudithistory.applier_id
     *
     * @return the value of bidrequestaudithistory.applier_id
     *
     * @mbggenerated
     */
    public Long getApplierId() {
        return applierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bidrequestaudithistory.applier_id
     *
     * @param applierId the value for bidrequestaudithistory.applier_id
     *
     * @mbggenerated
     */
    public void setApplierId(Long applierId) {
        this.applierId = applierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bidrequestaudithistory.bidRequestId
     *
     * @return the value of bidrequestaudithistory.bidRequestId
     *
     * @mbggenerated
     */
    public Long getBidrequestid() {
        return bidrequestid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bidrequestaudithistory.bidRequestId
     *
     * @param bidrequestid the value for bidrequestaudithistory.bidRequestId
     *
     * @mbggenerated
     */
    public void setBidrequestid(Long bidrequestid) {
        this.bidrequestid = bidrequestid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bidrequestaudithistory.auditType
     *
     * @return the value of bidrequestaudithistory.auditType
     *
     * @mbggenerated
     */
    public Byte getAudittype() {
        return audittype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bidrequestaudithistory.auditType
     *
     * @param audittype the value for bidrequestaudithistory.auditType
     *
     * @mbggenerated
     */
    public void setAudittype(Byte audittype) {
        this.audittype = audittype;
    }
}