package cn.carry.domain;

import java.math.BigDecimal;
import java.util.Date;

public class Bidrequest {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bidrequest.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bidrequest.version
     *
     * @mbggenerated
     */
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bidrequest.bidRequestType
     *
     * @mbggenerated
     */
    private Byte bidrequesttype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bidrequest.bidRequestState
     *
     * @mbggenerated
     */
    private Byte bidrequeststate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bidrequest.bidRequestAmount
     *
     * @mbggenerated
     */
    private BigDecimal bidrequestamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bidrequest.currentRate
     *
     * @mbggenerated
     */
    private BigDecimal currentrate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bidrequest.monthes2Return
     *
     * @mbggenerated
     */
    private Byte monthes2return;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bidrequest.bidCount
     *
     * @mbggenerated
     */
    private Integer bidcount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bidrequest.totalRewardAmount
     *
     * @mbggenerated
     */
    private BigDecimal totalrewardamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bidrequest.currentSum
     *
     * @mbggenerated
     */
    private BigDecimal currentsum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bidrequest.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bidrequest.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bidrequest.note
     *
     * @mbggenerated
     */
    private String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bidrequest.disableDate
     *
     * @mbggenerated
     */
    private Date disabledate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bidrequest.createuser_id
     *
     * @mbggenerated
     */
    private Long createuserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bidrequest.disableDays
     *
     * @mbggenerated
     */
    private Byte disabledays;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bidrequest.minBidAmount
     *
     * @mbggenerated
     */
    private BigDecimal minbidamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bidrequest.applyTime
     *
     * @mbggenerated
     */
    private Date applytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bidrequest.publishTime
     *
     * @mbggenerated
     */
    private Date publishtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bidrequest.id
     *
     * @return the value of bidrequest.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bidrequest.id
     *
     * @param id the value for bidrequest.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bidrequest.version
     *
     * @return the value of bidrequest.version
     *
     * @mbggenerated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bidrequest.version
     *
     * @param version the value for bidrequest.version
     *
     * @mbggenerated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bidrequest.bidRequestType
     *
     * @return the value of bidrequest.bidRequestType
     *
     * @mbggenerated
     */
    public Byte getBidrequesttype() {
        return bidrequesttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bidrequest.bidRequestType
     *
     * @param bidrequesttype the value for bidrequest.bidRequestType
     *
     * @mbggenerated
     */
    public void setBidrequesttype(Byte bidrequesttype) {
        this.bidrequesttype = bidrequesttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bidrequest.bidRequestState
     *
     * @return the value of bidrequest.bidRequestState
     *
     * @mbggenerated
     */
    public Byte getBidrequeststate() {
        return bidrequeststate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bidrequest.bidRequestState
     *
     * @param bidrequeststate the value for bidrequest.bidRequestState
     *
     * @mbggenerated
     */
    public void setBidrequeststate(Byte bidrequeststate) {
        this.bidrequeststate = bidrequeststate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bidrequest.bidRequestAmount
     *
     * @return the value of bidrequest.bidRequestAmount
     *
     * @mbggenerated
     */
    public BigDecimal getBidrequestamount() {
        return bidrequestamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bidrequest.bidRequestAmount
     *
     * @param bidrequestamount the value for bidrequest.bidRequestAmount
     *
     * @mbggenerated
     */
    public void setBidrequestamount(BigDecimal bidrequestamount) {
        this.bidrequestamount = bidrequestamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bidrequest.currentRate
     *
     * @return the value of bidrequest.currentRate
     *
     * @mbggenerated
     */
    public BigDecimal getCurrentrate() {
        return currentrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bidrequest.currentRate
     *
     * @param currentrate the value for bidrequest.currentRate
     *
     * @mbggenerated
     */
    public void setCurrentrate(BigDecimal currentrate) {
        this.currentrate = currentrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bidrequest.monthes2Return
     *
     * @return the value of bidrequest.monthes2Return
     *
     * @mbggenerated
     */
    public Byte getMonthes2return() {
        return monthes2return;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bidrequest.monthes2Return
     *
     * @param monthes2return the value for bidrequest.monthes2Return
     *
     * @mbggenerated
     */
    public void setMonthes2return(Byte monthes2return) {
        this.monthes2return = monthes2return;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bidrequest.bidCount
     *
     * @return the value of bidrequest.bidCount
     *
     * @mbggenerated
     */
    public Integer getBidcount() {
        return bidcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bidrequest.bidCount
     *
     * @param bidcount the value for bidrequest.bidCount
     *
     * @mbggenerated
     */
    public void setBidcount(Integer bidcount) {
        this.bidcount = bidcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bidrequest.totalRewardAmount
     *
     * @return the value of bidrequest.totalRewardAmount
     *
     * @mbggenerated
     */
    public BigDecimal getTotalrewardamount() {
        return totalrewardamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bidrequest.totalRewardAmount
     *
     * @param totalrewardamount the value for bidrequest.totalRewardAmount
     *
     * @mbggenerated
     */
    public void setTotalrewardamount(BigDecimal totalrewardamount) {
        this.totalrewardamount = totalrewardamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bidrequest.currentSum
     *
     * @return the value of bidrequest.currentSum
     *
     * @mbggenerated
     */
    public BigDecimal getCurrentsum() {
        return currentsum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bidrequest.currentSum
     *
     * @param currentsum the value for bidrequest.currentSum
     *
     * @mbggenerated
     */
    public void setCurrentsum(BigDecimal currentsum) {
        this.currentsum = currentsum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bidrequest.title
     *
     * @return the value of bidrequest.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bidrequest.title
     *
     * @param title the value for bidrequest.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bidrequest.description
     *
     * @return the value of bidrequest.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bidrequest.description
     *
     * @param description the value for bidrequest.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bidrequest.note
     *
     * @return the value of bidrequest.note
     *
     * @mbggenerated
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bidrequest.note
     *
     * @param note the value for bidrequest.note
     *
     * @mbggenerated
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bidrequest.disableDate
     *
     * @return the value of bidrequest.disableDate
     *
     * @mbggenerated
     */
    public Date getDisabledate() {
        return disabledate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bidrequest.disableDate
     *
     * @param disabledate the value for bidrequest.disableDate
     *
     * @mbggenerated
     */
    public void setDisabledate(Date disabledate) {
        this.disabledate = disabledate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bidrequest.createuser_id
     *
     * @return the value of bidrequest.createuser_id
     *
     * @mbggenerated
     */
    public Long getCreateuserId() {
        return createuserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bidrequest.createuser_id
     *
     * @param createuserId the value for bidrequest.createuser_id
     *
     * @mbggenerated
     */
    public void setCreateuserId(Long createuserId) {
        this.createuserId = createuserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bidrequest.disableDays
     *
     * @return the value of bidrequest.disableDays
     *
     * @mbggenerated
     */
    public Byte getDisabledays() {
        return disabledays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bidrequest.disableDays
     *
     * @param disabledays the value for bidrequest.disableDays
     *
     * @mbggenerated
     */
    public void setDisabledays(Byte disabledays) {
        this.disabledays = disabledays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bidrequest.minBidAmount
     *
     * @return the value of bidrequest.minBidAmount
     *
     * @mbggenerated
     */
    public BigDecimal getMinbidamount() {
        return minbidamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bidrequest.minBidAmount
     *
     * @param minbidamount the value for bidrequest.minBidAmount
     *
     * @mbggenerated
     */
    public void setMinbidamount(BigDecimal minbidamount) {
        this.minbidamount = minbidamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bidrequest.applyTime
     *
     * @return the value of bidrequest.applyTime
     *
     * @mbggenerated
     */
    public Date getApplytime() {
        return applytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bidrequest.applyTime
     *
     * @param applytime the value for bidrequest.applyTime
     *
     * @mbggenerated
     */
    public void setApplytime(Date applytime) {
        this.applytime = applytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bidrequest.publishTime
     *
     * @return the value of bidrequest.publishTime
     *
     * @mbggenerated
     */
    public Date getPublishtime() {
        return publishtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bidrequest.publishTime
     *
     * @param publishtime the value for bidrequest.publishTime
     *
     * @mbggenerated
     */
    public void setPublishtime(Date publishtime) {
        this.publishtime = publishtime;
    }
}