package cn.carry.domain;

public class Companybankinfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column companybankinfo.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column companybankinfo.bankname
     *
     * @mbggenerated
     */
    private String bankname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column companybankinfo.accountname
     *
     * @mbggenerated
     */
    private String accountname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column companybankinfo.banknumber
     *
     * @mbggenerated
     */
    private String banknumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column companybankinfo.bankforkname
     *
     * @mbggenerated
     */
    private String bankforkname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column companybankinfo.id
     *
     * @return the value of companybankinfo.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column companybankinfo.id
     *
     * @param id the value for companybankinfo.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column companybankinfo.bankname
     *
     * @return the value of companybankinfo.bankname
     *
     * @mbggenerated
     */
    public String getBankname() {
        return bankname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column companybankinfo.bankname
     *
     * @param bankname the value for companybankinfo.bankname
     *
     * @mbggenerated
     */
    public void setBankname(String bankname) {
        this.bankname = bankname == null ? null : bankname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column companybankinfo.accountname
     *
     * @return the value of companybankinfo.accountname
     *
     * @mbggenerated
     */
    public String getAccountname() {
        return accountname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column companybankinfo.accountname
     *
     * @param accountname the value for companybankinfo.accountname
     *
     * @mbggenerated
     */
    public void setAccountname(String accountname) {
        this.accountname = accountname == null ? null : accountname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column companybankinfo.banknumber
     *
     * @return the value of companybankinfo.banknumber
     *
     * @mbggenerated
     */
    public String getBanknumber() {
        return banknumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column companybankinfo.banknumber
     *
     * @param banknumber the value for companybankinfo.banknumber
     *
     * @mbggenerated
     */
    public void setBanknumber(String banknumber) {
        this.banknumber = banknumber == null ? null : banknumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column companybankinfo.bankforkname
     *
     * @return the value of companybankinfo.bankforkname
     *
     * @mbggenerated
     */
    public String getBankforkname() {
        return bankforkname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column companybankinfo.bankforkname
     *
     * @param bankforkname the value for companybankinfo.bankforkname
     *
     * @mbggenerated
     */
    public void setBankforkname(String bankforkname) {
        this.bankforkname = bankforkname == null ? null : bankforkname.trim();
    }
}