package cn.carry.domain;

import java.util.Date;

public class Iplog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iplog.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iplog.ip
     *
     * @mbggenerated
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iplog.loginState
     *
     * @mbggenerated
     */
    private Byte loginstate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iplog.username
     *
     * @mbggenerated
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iplog.loginInfoId
     *
     * @mbggenerated
     */
    private Long logininfoid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iplog.loginType
     *
     * @mbggenerated
     */
    private Byte logintype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iplog.loginTime
     *
     * @mbggenerated
     */
    private Date logintime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iplog.id
     *
     * @return the value of iplog.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iplog.id
     *
     * @param id the value for iplog.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iplog.ip
     *
     * @return the value of iplog.ip
     *
     * @mbggenerated
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iplog.ip
     *
     * @param ip the value for iplog.ip
     *
     * @mbggenerated
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iplog.loginState
     *
     * @return the value of iplog.loginState
     *
     * @mbggenerated
     */
    public Byte getLoginstate() {
        return loginstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iplog.loginState
     *
     * @param loginstate the value for iplog.loginState
     *
     * @mbggenerated
     */
    public void setLoginstate(Byte loginstate) {
        this.loginstate = loginstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iplog.username
     *
     * @return the value of iplog.username
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iplog.username
     *
     * @param username the value for iplog.username
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iplog.loginInfoId
     *
     * @return the value of iplog.loginInfoId
     *
     * @mbggenerated
     */
    public Long getLogininfoid() {
        return logininfoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iplog.loginInfoId
     *
     * @param logininfoid the value for iplog.loginInfoId
     *
     * @mbggenerated
     */
    public void setLogininfoid(Long logininfoid) {
        this.logininfoid = logininfoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iplog.loginType
     *
     * @return the value of iplog.loginType
     *
     * @mbggenerated
     */
    public Byte getLogintype() {
        return logintype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iplog.loginType
     *
     * @param logintype the value for iplog.loginType
     *
     * @mbggenerated
     */
    public void setLogintype(Byte logintype) {
        this.logintype = logintype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column iplog.loginTime
     *
     * @return the value of iplog.loginTime
     *
     * @mbggenerated
     */
    public Date getLogintime() {
        return logintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column iplog.loginTime
     *
     * @param logintime the value for iplog.loginTime
     *
     * @mbggenerated
     */
    public void setLogintime(Date logintime) {
        this.logintime = logintime;
    }
}