package cn.carry.domain;

import java.math.BigDecimal;
import java.util.Date;

public class Paymentschedule {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paymentschedule.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paymentschedule.deadLine
     *
     * @mbggenerated
     */
    private Date deadline;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paymentschedule.payDate
     *
     * @mbggenerated
     */
    private Date paydate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paymentschedule.totalAmount
     *
     * @mbggenerated
     */
    private BigDecimal totalamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paymentschedule.principal
     *
     * @mbggenerated
     */
    private BigDecimal principal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paymentschedule.interest
     *
     * @mbggenerated
     */
    private BigDecimal interest;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paymentschedule.monthIndex
     *
     * @mbggenerated
     */
    private Byte monthindex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paymentschedule.state
     *
     * @mbggenerated
     */
    private Byte state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paymentschedule.bidRequestType
     *
     * @mbggenerated
     */
    private Byte bidrequesttype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paymentschedule.returnType
     *
     * @mbggenerated
     */
    private Byte returntype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paymentschedule.bidrequest_id
     *
     * @mbggenerated
     */
    private Long bidrequestId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paymentschedule.biduser_id
     *
     * @mbggenerated
     */
    private Long biduserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paymentschedule.bidRequestTitle
     *
     * @mbggenerated
     */
    private String bidrequesttitle;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paymentschedule.id
     *
     * @return the value of paymentschedule.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paymentschedule.id
     *
     * @param id the value for paymentschedule.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paymentschedule.deadLine
     *
     * @return the value of paymentschedule.deadLine
     *
     * @mbggenerated
     */
    public Date getDeadline() {
        return deadline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paymentschedule.deadLine
     *
     * @param deadline the value for paymentschedule.deadLine
     *
     * @mbggenerated
     */
    public void setDeadline(Date deadline) {
        this.deadline = deadline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paymentschedule.payDate
     *
     * @return the value of paymentschedule.payDate
     *
     * @mbggenerated
     */
    public Date getPaydate() {
        return paydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paymentschedule.payDate
     *
     * @param paydate the value for paymentschedule.payDate
     *
     * @mbggenerated
     */
    public void setPaydate(Date paydate) {
        this.paydate = paydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paymentschedule.totalAmount
     *
     * @return the value of paymentschedule.totalAmount
     *
     * @mbggenerated
     */
    public BigDecimal getTotalamount() {
        return totalamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paymentschedule.totalAmount
     *
     * @param totalamount the value for paymentschedule.totalAmount
     *
     * @mbggenerated
     */
    public void setTotalamount(BigDecimal totalamount) {
        this.totalamount = totalamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paymentschedule.principal
     *
     * @return the value of paymentschedule.principal
     *
     * @mbggenerated
     */
    public BigDecimal getPrincipal() {
        return principal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paymentschedule.principal
     *
     * @param principal the value for paymentschedule.principal
     *
     * @mbggenerated
     */
    public void setPrincipal(BigDecimal principal) {
        this.principal = principal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paymentschedule.interest
     *
     * @return the value of paymentschedule.interest
     *
     * @mbggenerated
     */
    public BigDecimal getInterest() {
        return interest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paymentschedule.interest
     *
     * @param interest the value for paymentschedule.interest
     *
     * @mbggenerated
     */
    public void setInterest(BigDecimal interest) {
        this.interest = interest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paymentschedule.monthIndex
     *
     * @return the value of paymentschedule.monthIndex
     *
     * @mbggenerated
     */
    public Byte getMonthindex() {
        return monthindex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paymentschedule.monthIndex
     *
     * @param monthindex the value for paymentschedule.monthIndex
     *
     * @mbggenerated
     */
    public void setMonthindex(Byte monthindex) {
        this.monthindex = monthindex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paymentschedule.state
     *
     * @return the value of paymentschedule.state
     *
     * @mbggenerated
     */
    public Byte getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paymentschedule.state
     *
     * @param state the value for paymentschedule.state
     *
     * @mbggenerated
     */
    public void setState(Byte state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paymentschedule.bidRequestType
     *
     * @return the value of paymentschedule.bidRequestType
     *
     * @mbggenerated
     */
    public Byte getBidrequesttype() {
        return bidrequesttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paymentschedule.bidRequestType
     *
     * @param bidrequesttype the value for paymentschedule.bidRequestType
     *
     * @mbggenerated
     */
    public void setBidrequesttype(Byte bidrequesttype) {
        this.bidrequesttype = bidrequesttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paymentschedule.returnType
     *
     * @return the value of paymentschedule.returnType
     *
     * @mbggenerated
     */
    public Byte getReturntype() {
        return returntype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paymentschedule.returnType
     *
     * @param returntype the value for paymentschedule.returnType
     *
     * @mbggenerated
     */
    public void setReturntype(Byte returntype) {
        this.returntype = returntype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paymentschedule.bidrequest_id
     *
     * @return the value of paymentschedule.bidrequest_id
     *
     * @mbggenerated
     */
    public Long getBidrequestId() {
        return bidrequestId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paymentschedule.bidrequest_id
     *
     * @param bidrequestId the value for paymentschedule.bidrequest_id
     *
     * @mbggenerated
     */
    public void setBidrequestId(Long bidrequestId) {
        this.bidrequestId = bidrequestId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paymentschedule.biduser_id
     *
     * @return the value of paymentschedule.biduser_id
     *
     * @mbggenerated
     */
    public Long getBiduserId() {
        return biduserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paymentschedule.biduser_id
     *
     * @param biduserId the value for paymentschedule.biduser_id
     *
     * @mbggenerated
     */
    public void setBiduserId(Long biduserId) {
        this.biduserId = biduserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paymentschedule.bidRequestTitle
     *
     * @return the value of paymentschedule.bidRequestTitle
     *
     * @mbggenerated
     */
    public String getBidrequesttitle() {
        return bidrequesttitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paymentschedule.bidRequestTitle
     *
     * @param bidrequesttitle the value for paymentschedule.bidRequestTitle
     *
     * @mbggenerated
     */
    public void setBidrequesttitle(String bidrequesttitle) {
        this.bidrequesttitle = bidrequesttitle == null ? null : bidrequesttitle.trim();
    }
}