package cn.carry.domain;

import java.math.BigDecimal;
import java.util.Date;

public class Paymentscheduledetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paymentscheduledetail.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paymentscheduledetail.bidamount
     *
     * @mbggenerated
     */
    private BigDecimal bidamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paymentscheduledetail.bid_id
     *
     * @mbggenerated
     */
    private Long bidId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paymentscheduledetail.totalamount
     *
     * @mbggenerated
     */
    private BigDecimal totalamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paymentscheduledetail.principal
     *
     * @mbggenerated
     */
    private BigDecimal principal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paymentscheduledetail.interest
     *
     * @mbggenerated
     */
    private BigDecimal interest;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paymentscheduledetail.monthindex
     *
     * @mbggenerated
     */
    private Byte monthindex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paymentscheduledetail.deadline
     *
     * @mbggenerated
     */
    private Date deadline;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paymentscheduledetail.bidrequest_id
     *
     * @mbggenerated
     */
    private Long bidrequestId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paymentscheduledetail.paydate
     *
     * @mbggenerated
     */
    private Date paydate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paymentscheduledetail.returntype
     *
     * @mbggenerated
     */
    private Byte returntype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paymentscheduledetail.paymentschedule_id
     *
     * @mbggenerated
     */
    private Long paymentscheduleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paymentscheduledetail.fromlogininfo_id
     *
     * @mbggenerated
     */
    private Long fromlogininfoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paymentscheduledetail.tologininfo_id
     *
     * @mbggenerated
     */
    private Long tologininfoId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paymentscheduledetail.id
     *
     * @return the value of paymentscheduledetail.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paymentscheduledetail.id
     *
     * @param id the value for paymentscheduledetail.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paymentscheduledetail.bidamount
     *
     * @return the value of paymentscheduledetail.bidamount
     *
     * @mbggenerated
     */
    public BigDecimal getBidamount() {
        return bidamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paymentscheduledetail.bidamount
     *
     * @param bidamount the value for paymentscheduledetail.bidamount
     *
     * @mbggenerated
     */
    public void setBidamount(BigDecimal bidamount) {
        this.bidamount = bidamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paymentscheduledetail.bid_id
     *
     * @return the value of paymentscheduledetail.bid_id
     *
     * @mbggenerated
     */
    public Long getBidId() {
        return bidId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paymentscheduledetail.bid_id
     *
     * @param bidId the value for paymentscheduledetail.bid_id
     *
     * @mbggenerated
     */
    public void setBidId(Long bidId) {
        this.bidId = bidId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paymentscheduledetail.totalamount
     *
     * @return the value of paymentscheduledetail.totalamount
     *
     * @mbggenerated
     */
    public BigDecimal getTotalamount() {
        return totalamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paymentscheduledetail.totalamount
     *
     * @param totalamount the value for paymentscheduledetail.totalamount
     *
     * @mbggenerated
     */
    public void setTotalamount(BigDecimal totalamount) {
        this.totalamount = totalamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paymentscheduledetail.principal
     *
     * @return the value of paymentscheduledetail.principal
     *
     * @mbggenerated
     */
    public BigDecimal getPrincipal() {
        return principal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paymentscheduledetail.principal
     *
     * @param principal the value for paymentscheduledetail.principal
     *
     * @mbggenerated
     */
    public void setPrincipal(BigDecimal principal) {
        this.principal = principal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paymentscheduledetail.interest
     *
     * @return the value of paymentscheduledetail.interest
     *
     * @mbggenerated
     */
    public BigDecimal getInterest() {
        return interest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paymentscheduledetail.interest
     *
     * @param interest the value for paymentscheduledetail.interest
     *
     * @mbggenerated
     */
    public void setInterest(BigDecimal interest) {
        this.interest = interest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paymentscheduledetail.monthindex
     *
     * @return the value of paymentscheduledetail.monthindex
     *
     * @mbggenerated
     */
    public Byte getMonthindex() {
        return monthindex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paymentscheduledetail.monthindex
     *
     * @param monthindex the value for paymentscheduledetail.monthindex
     *
     * @mbggenerated
     */
    public void setMonthindex(Byte monthindex) {
        this.monthindex = monthindex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paymentscheduledetail.deadline
     *
     * @return the value of paymentscheduledetail.deadline
     *
     * @mbggenerated
     */
    public Date getDeadline() {
        return deadline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paymentscheduledetail.deadline
     *
     * @param deadline the value for paymentscheduledetail.deadline
     *
     * @mbggenerated
     */
    public void setDeadline(Date deadline) {
        this.deadline = deadline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paymentscheduledetail.bidrequest_id
     *
     * @return the value of paymentscheduledetail.bidrequest_id
     *
     * @mbggenerated
     */
    public Long getBidrequestId() {
        return bidrequestId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paymentscheduledetail.bidrequest_id
     *
     * @param bidrequestId the value for paymentscheduledetail.bidrequest_id
     *
     * @mbggenerated
     */
    public void setBidrequestId(Long bidrequestId) {
        this.bidrequestId = bidrequestId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paymentscheduledetail.paydate
     *
     * @return the value of paymentscheduledetail.paydate
     *
     * @mbggenerated
     */
    public Date getPaydate() {
        return paydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paymentscheduledetail.paydate
     *
     * @param paydate the value for paymentscheduledetail.paydate
     *
     * @mbggenerated
     */
    public void setPaydate(Date paydate) {
        this.paydate = paydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paymentscheduledetail.returntype
     *
     * @return the value of paymentscheduledetail.returntype
     *
     * @mbggenerated
     */
    public Byte getReturntype() {
        return returntype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paymentscheduledetail.returntype
     *
     * @param returntype the value for paymentscheduledetail.returntype
     *
     * @mbggenerated
     */
    public void setReturntype(Byte returntype) {
        this.returntype = returntype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paymentscheduledetail.paymentschedule_id
     *
     * @return the value of paymentscheduledetail.paymentschedule_id
     *
     * @mbggenerated
     */
    public Long getPaymentscheduleId() {
        return paymentscheduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paymentscheduledetail.paymentschedule_id
     *
     * @param paymentscheduleId the value for paymentscheduledetail.paymentschedule_id
     *
     * @mbggenerated
     */
    public void setPaymentscheduleId(Long paymentscheduleId) {
        this.paymentscheduleId = paymentscheduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paymentscheduledetail.fromlogininfo_id
     *
     * @return the value of paymentscheduledetail.fromlogininfo_id
     *
     * @mbggenerated
     */
    public Long getFromlogininfoId() {
        return fromlogininfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paymentscheduledetail.fromlogininfo_id
     *
     * @param fromlogininfoId the value for paymentscheduledetail.fromlogininfo_id
     *
     * @mbggenerated
     */
    public void setFromlogininfoId(Long fromlogininfoId) {
        this.fromlogininfoId = fromlogininfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paymentscheduledetail.tologininfo_id
     *
     * @return the value of paymentscheduledetail.tologininfo_id
     *
     * @mbggenerated
     */
    public Long getTologininfoId() {
        return tologininfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paymentscheduledetail.tologininfo_id
     *
     * @param tologininfoId the value for paymentscheduledetail.tologininfo_id
     *
     * @mbggenerated
     */
    public void setTologininfoId(Long tologininfoId) {
        this.tologininfoId = tologininfoId;
    }
}