package cn.carry.domain;

import java.util.Date;

public class Realauth {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column realauth.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column realauth.realname
     *
     * @mbggenerated
     */
    private String realname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column realauth.sex
     *
     * @mbggenerated
     */
    private Byte sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column realauth.birthDate
     *
     * @mbggenerated
     */
    private String birthdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column realauth.idNumber
     *
     * @mbggenerated
     */
    private String idnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column realauth.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column realauth.state
     *
     * @mbggenerated
     */
    private Byte state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column realauth.image1
     *
     * @mbggenerated
     */
    private String image1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column realauth.image2
     *
     * @mbggenerated
     */
    private String image2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column realauth.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column realauth.auditTime
     *
     * @mbggenerated
     */
    private Date audittime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column realauth.applyTime
     *
     * @mbggenerated
     */
    private Date applytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column realauth.auditor_id
     *
     * @mbggenerated
     */
    private Long auditorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column realauth.applier_id
     *
     * @mbggenerated
     */
    private Long applierId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column realauth.id
     *
     * @return the value of realauth.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column realauth.id
     *
     * @param id the value for realauth.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column realauth.realname
     *
     * @return the value of realauth.realname
     *
     * @mbggenerated
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column realauth.realname
     *
     * @param realname the value for realauth.realname
     *
     * @mbggenerated
     */
    public void setRealname(String realname) {
        this.realname = realname == null ? null : realname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column realauth.sex
     *
     * @return the value of realauth.sex
     *
     * @mbggenerated
     */
    public Byte getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column realauth.sex
     *
     * @param sex the value for realauth.sex
     *
     * @mbggenerated
     */
    public void setSex(Byte sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column realauth.birthDate
     *
     * @return the value of realauth.birthDate
     *
     * @mbggenerated
     */
    public String getBirthdate() {
        return birthdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column realauth.birthDate
     *
     * @param birthdate the value for realauth.birthDate
     *
     * @mbggenerated
     */
    public void setBirthdate(String birthdate) {
        this.birthdate = birthdate == null ? null : birthdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column realauth.idNumber
     *
     * @return the value of realauth.idNumber
     *
     * @mbggenerated
     */
    public String getIdnumber() {
        return idnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column realauth.idNumber
     *
     * @param idnumber the value for realauth.idNumber
     *
     * @mbggenerated
     */
    public void setIdnumber(String idnumber) {
        this.idnumber = idnumber == null ? null : idnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column realauth.address
     *
     * @return the value of realauth.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column realauth.address
     *
     * @param address the value for realauth.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column realauth.state
     *
     * @return the value of realauth.state
     *
     * @mbggenerated
     */
    public Byte getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column realauth.state
     *
     * @param state the value for realauth.state
     *
     * @mbggenerated
     */
    public void setState(Byte state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column realauth.image1
     *
     * @return the value of realauth.image1
     *
     * @mbggenerated
     */
    public String getImage1() {
        return image1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column realauth.image1
     *
     * @param image1 the value for realauth.image1
     *
     * @mbggenerated
     */
    public void setImage1(String image1) {
        this.image1 = image1 == null ? null : image1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column realauth.image2
     *
     * @return the value of realauth.image2
     *
     * @mbggenerated
     */
    public String getImage2() {
        return image2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column realauth.image2
     *
     * @param image2 the value for realauth.image2
     *
     * @mbggenerated
     */
    public void setImage2(String image2) {
        this.image2 = image2 == null ? null : image2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column realauth.remark
     *
     * @return the value of realauth.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column realauth.remark
     *
     * @param remark the value for realauth.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column realauth.auditTime
     *
     * @return the value of realauth.auditTime
     *
     * @mbggenerated
     */
    public Date getAudittime() {
        return audittime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column realauth.auditTime
     *
     * @param audittime the value for realauth.auditTime
     *
     * @mbggenerated
     */
    public void setAudittime(Date audittime) {
        this.audittime = audittime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column realauth.applyTime
     *
     * @return the value of realauth.applyTime
     *
     * @mbggenerated
     */
    public Date getApplytime() {
        return applytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column realauth.applyTime
     *
     * @param applytime the value for realauth.applyTime
     *
     * @mbggenerated
     */
    public void setApplytime(Date applytime) {
        this.applytime = applytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column realauth.auditor_id
     *
     * @return the value of realauth.auditor_id
     *
     * @mbggenerated
     */
    public Long getAuditorId() {
        return auditorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column realauth.auditor_id
     *
     * @param auditorId the value for realauth.auditor_id
     *
     * @mbggenerated
     */
    public void setAuditorId(Long auditorId) {
        this.auditorId = auditorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column realauth.applier_id
     *
     * @return the value of realauth.applier_id
     *
     * @mbggenerated
     */
    public Long getApplierId() {
        return applierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column realauth.applier_id
     *
     * @param applierId the value for realauth.applier_id
     *
     * @mbggenerated
     */
    public void setApplierId(Long applierId) {
        this.applierId = applierId;
    }
}