package cn.carry.domain;

import java.math.BigDecimal;
import java.util.Date;

public class Rechargeoffline {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rechargeoffline.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rechargeoffline.state
     *
     * @mbggenerated
     */
    private Byte state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rechargeoffline.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rechargeoffline.auditTime
     *
     * @mbggenerated
     */
    private Date audittime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rechargeoffline.applyTime
     *
     * @mbggenerated
     */
    private Date applytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rechargeoffline.auditor_id
     *
     * @mbggenerated
     */
    private Long auditorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rechargeoffline.applier_id
     *
     * @mbggenerated
     */
    private Long applierId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rechargeoffline.tradeCode
     *
     * @mbggenerated
     */
    private String tradecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rechargeoffline.tradeTime
     *
     * @mbggenerated
     */
    private Date tradetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rechargeoffline.amount
     *
     * @mbggenerated
     */
    private BigDecimal amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rechargeoffline.note
     *
     * @mbggenerated
     */
    private String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rechargeoffline.bankinfo_id
     *
     * @mbggenerated
     */
    private Long bankinfoId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rechargeoffline.id
     *
     * @return the value of rechargeoffline.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rechargeoffline.id
     *
     * @param id the value for rechargeoffline.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rechargeoffline.state
     *
     * @return the value of rechargeoffline.state
     *
     * @mbggenerated
     */
    public Byte getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rechargeoffline.state
     *
     * @param state the value for rechargeoffline.state
     *
     * @mbggenerated
     */
    public void setState(Byte state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rechargeoffline.remark
     *
     * @return the value of rechargeoffline.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rechargeoffline.remark
     *
     * @param remark the value for rechargeoffline.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rechargeoffline.auditTime
     *
     * @return the value of rechargeoffline.auditTime
     *
     * @mbggenerated
     */
    public Date getAudittime() {
        return audittime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rechargeoffline.auditTime
     *
     * @param audittime the value for rechargeoffline.auditTime
     *
     * @mbggenerated
     */
    public void setAudittime(Date audittime) {
        this.audittime = audittime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rechargeoffline.applyTime
     *
     * @return the value of rechargeoffline.applyTime
     *
     * @mbggenerated
     */
    public Date getApplytime() {
        return applytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rechargeoffline.applyTime
     *
     * @param applytime the value for rechargeoffline.applyTime
     *
     * @mbggenerated
     */
    public void setApplytime(Date applytime) {
        this.applytime = applytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rechargeoffline.auditor_id
     *
     * @return the value of rechargeoffline.auditor_id
     *
     * @mbggenerated
     */
    public Long getAuditorId() {
        return auditorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rechargeoffline.auditor_id
     *
     * @param auditorId the value for rechargeoffline.auditor_id
     *
     * @mbggenerated
     */
    public void setAuditorId(Long auditorId) {
        this.auditorId = auditorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rechargeoffline.applier_id
     *
     * @return the value of rechargeoffline.applier_id
     *
     * @mbggenerated
     */
    public Long getApplierId() {
        return applierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rechargeoffline.applier_id
     *
     * @param applierId the value for rechargeoffline.applier_id
     *
     * @mbggenerated
     */
    public void setApplierId(Long applierId) {
        this.applierId = applierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rechargeoffline.tradeCode
     *
     * @return the value of rechargeoffline.tradeCode
     *
     * @mbggenerated
     */
    public String getTradecode() {
        return tradecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rechargeoffline.tradeCode
     *
     * @param tradecode the value for rechargeoffline.tradeCode
     *
     * @mbggenerated
     */
    public void setTradecode(String tradecode) {
        this.tradecode = tradecode == null ? null : tradecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rechargeoffline.tradeTime
     *
     * @return the value of rechargeoffline.tradeTime
     *
     * @mbggenerated
     */
    public Date getTradetime() {
        return tradetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rechargeoffline.tradeTime
     *
     * @param tradetime the value for rechargeoffline.tradeTime
     *
     * @mbggenerated
     */
    public void setTradetime(Date tradetime) {
        this.tradetime = tradetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rechargeoffline.amount
     *
     * @return the value of rechargeoffline.amount
     *
     * @mbggenerated
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rechargeoffline.amount
     *
     * @param amount the value for rechargeoffline.amount
     *
     * @mbggenerated
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rechargeoffline.note
     *
     * @return the value of rechargeoffline.note
     *
     * @mbggenerated
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rechargeoffline.note
     *
     * @param note the value for rechargeoffline.note
     *
     * @mbggenerated
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rechargeoffline.bankinfo_id
     *
     * @return the value of rechargeoffline.bankinfo_id
     *
     * @mbggenerated
     */
    public Long getBankinfoId() {
        return bankinfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rechargeoffline.bankinfo_id
     *
     * @param bankinfoId the value for rechargeoffline.bankinfo_id
     *
     * @mbggenerated
     */
    public void setBankinfoId(Long bankinfoId) {
        this.bankinfoId = bankinfoId;
    }
}