package cn.carry.domain;

public class Systemdictionaryitem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column systemdictionaryitem.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column systemdictionaryitem.parentId
     *
     * @mbggenerated
     */
    private Long parentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column systemdictionaryitem.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column systemdictionaryitem.tvalue
     *
     * @mbggenerated
     */
    private String tvalue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column systemdictionaryitem.sequence
     *
     * @mbggenerated
     */
    private Byte sequence;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column systemdictionaryitem.intro
     *
     * @mbggenerated
     */
    private String intro;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column systemdictionaryitem.id
     *
     * @return the value of systemdictionaryitem.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column systemdictionaryitem.id
     *
     * @param id the value for systemdictionaryitem.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column systemdictionaryitem.parentId
     *
     * @return the value of systemdictionaryitem.parentId
     *
     * @mbggenerated
     */
    public Long getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column systemdictionaryitem.parentId
     *
     * @param parentid the value for systemdictionaryitem.parentId
     *
     * @mbggenerated
     */
    public void setParentid(Long parentid) {
        this.parentid = parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column systemdictionaryitem.title
     *
     * @return the value of systemdictionaryitem.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column systemdictionaryitem.title
     *
     * @param title the value for systemdictionaryitem.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column systemdictionaryitem.tvalue
     *
     * @return the value of systemdictionaryitem.tvalue
     *
     * @mbggenerated
     */
    public String getTvalue() {
        return tvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column systemdictionaryitem.tvalue
     *
     * @param tvalue the value for systemdictionaryitem.tvalue
     *
     * @mbggenerated
     */
    public void setTvalue(String tvalue) {
        this.tvalue = tvalue == null ? null : tvalue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column systemdictionaryitem.sequence
     *
     * @return the value of systemdictionaryitem.sequence
     *
     * @mbggenerated
     */
    public Byte getSequence() {
        return sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column systemdictionaryitem.sequence
     *
     * @param sequence the value for systemdictionaryitem.sequence
     *
     * @mbggenerated
     */
    public void setSequence(Byte sequence) {
        this.sequence = sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column systemdictionaryitem.intro
     *
     * @return the value of systemdictionaryitem.intro
     *
     * @mbggenerated
     */
    public String getIntro() {
        return intro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column systemdictionaryitem.intro
     *
     * @param intro the value for systemdictionaryitem.intro
     *
     * @mbggenerated
     */
    public void setIntro(String intro) {
        this.intro = intro == null ? null : intro.trim();
    }
}