package cn.carry.domain;

import java.math.BigDecimal;
import java.util.Date;

public class Systemaccount {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column systemaccount.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column systemaccount.version
     *
     * @mbggenerated
     */
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column systemaccount.beginDate
     *
     * @mbggenerated
     */
    private Date begindate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column systemaccount.endDate
     *
     * @mbggenerated
     */
    private Date enddate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column systemaccount.createdate
     *
     * @mbggenerated
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column systemaccount.totalbalance
     *
     * @mbggenerated
     */
    private BigDecimal totalbalance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column systemaccount.freezedamount
     *
     * @mbggenerated
     */
    private BigDecimal freezedamount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column systemaccount.id
     *
     * @return the value of systemaccount.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column systemaccount.id
     *
     * @param id the value for systemaccount.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column systemaccount.version
     *
     * @return the value of systemaccount.version
     *
     * @mbggenerated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column systemaccount.version
     *
     * @param version the value for systemaccount.version
     *
     * @mbggenerated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column systemaccount.beginDate
     *
     * @return the value of systemaccount.beginDate
     *
     * @mbggenerated
     */
    public Date getBegindate() {
        return begindate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column systemaccount.beginDate
     *
     * @param begindate the value for systemaccount.beginDate
     *
     * @mbggenerated
     */
    public void setBegindate(Date begindate) {
        this.begindate = begindate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column systemaccount.endDate
     *
     * @return the value of systemaccount.endDate
     *
     * @mbggenerated
     */
    public Date getEnddate() {
        return enddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column systemaccount.endDate
     *
     * @param enddate the value for systemaccount.endDate
     *
     * @mbggenerated
     */
    public void setEnddate(Date enddate) {
        this.enddate = enddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column systemaccount.createdate
     *
     * @return the value of systemaccount.createdate
     *
     * @mbggenerated
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column systemaccount.createdate
     *
     * @param createdate the value for systemaccount.createdate
     *
     * @mbggenerated
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column systemaccount.totalbalance
     *
     * @return the value of systemaccount.totalbalance
     *
     * @mbggenerated
     */
    public BigDecimal getTotalbalance() {
        return totalbalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column systemaccount.totalbalance
     *
     * @param totalbalance the value for systemaccount.totalbalance
     *
     * @mbggenerated
     */
    public void setTotalbalance(BigDecimal totalbalance) {
        this.totalbalance = totalbalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column systemaccount.freezedamount
     *
     * @return the value of systemaccount.freezedamount
     *
     * @mbggenerated
     */
    public BigDecimal getFreezedamount() {
        return freezedamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column systemaccount.freezedamount
     *
     * @param freezedamount the value for systemaccount.freezedamount
     *
     * @mbggenerated
     */
    public void setFreezedamount(BigDecimal freezedamount) {
        this.freezedamount = freezedamount;
    }
}