package cn.carry.domain;

import java.util.Date;

public class Userfile {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userfile.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userfile.state
     *
     * @mbggenerated
     */
    private Byte state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userfile.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userfile.auditTime
     *
     * @mbggenerated
     */
    private Date audittime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userfile.applyTime
     *
     * @mbggenerated
     */
    private Date applytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userfile.auditor_id
     *
     * @mbggenerated
     */
    private Long auditorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userfile.applier_id
     *
     * @mbggenerated
     */
    private Long applierId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userfile.score
     *
     * @mbggenerated
     */
    private Byte score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userfile.file
     *
     * @mbggenerated
     */
    private String file;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userfile.filetype_id
     *
     * @mbggenerated
     */
    private Long filetypeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userfile.id
     *
     * @return the value of userfile.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userfile.id
     *
     * @param id the value for userfile.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userfile.state
     *
     * @return the value of userfile.state
     *
     * @mbggenerated
     */
    public Byte getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userfile.state
     *
     * @param state the value for userfile.state
     *
     * @mbggenerated
     */
    public void setState(Byte state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userfile.remark
     *
     * @return the value of userfile.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userfile.remark
     *
     * @param remark the value for userfile.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userfile.auditTime
     *
     * @return the value of userfile.auditTime
     *
     * @mbggenerated
     */
    public Date getAudittime() {
        return audittime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userfile.auditTime
     *
     * @param audittime the value for userfile.auditTime
     *
     * @mbggenerated
     */
    public void setAudittime(Date audittime) {
        this.audittime = audittime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userfile.applyTime
     *
     * @return the value of userfile.applyTime
     *
     * @mbggenerated
     */
    public Date getApplytime() {
        return applytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userfile.applyTime
     *
     * @param applytime the value for userfile.applyTime
     *
     * @mbggenerated
     */
    public void setApplytime(Date applytime) {
        this.applytime = applytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userfile.auditor_id
     *
     * @return the value of userfile.auditor_id
     *
     * @mbggenerated
     */
    public Long getAuditorId() {
        return auditorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userfile.auditor_id
     *
     * @param auditorId the value for userfile.auditor_id
     *
     * @mbggenerated
     */
    public void setAuditorId(Long auditorId) {
        this.auditorId = auditorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userfile.applier_id
     *
     * @return the value of userfile.applier_id
     *
     * @mbggenerated
     */
    public Long getApplierId() {
        return applierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userfile.applier_id
     *
     * @param applierId the value for userfile.applier_id
     *
     * @mbggenerated
     */
    public void setApplierId(Long applierId) {
        this.applierId = applierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userfile.score
     *
     * @return the value of userfile.score
     *
     * @mbggenerated
     */
    public Byte getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userfile.score
     *
     * @param score the value for userfile.score
     *
     * @mbggenerated
     */
    public void setScore(Byte score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userfile.file
     *
     * @return the value of userfile.file
     *
     * @mbggenerated
     */
    public String getFile() {
        return file;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userfile.file
     *
     * @param file the value for userfile.file
     *
     * @mbggenerated
     */
    public void setFile(String file) {
        this.file = file == null ? null : file.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userfile.filetype_id
     *
     * @return the value of userfile.filetype_id
     *
     * @mbggenerated
     */
    public Long getFiletypeId() {
        return filetypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userfile.filetype_id
     *
     * @param filetypeId the value for userfile.filetype_id
     *
     * @mbggenerated
     */
    public void setFiletypeId(Long filetypeId) {
        this.filetypeId = filetypeId;
    }
}