package cn.carry.domain;

public class Userinfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.version
     *
     * @mbggenerated
     */
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.bitState
     *
     * @mbggenerated
     */
    private Long bitstate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.realName
     *
     * @mbggenerated
     */
    private String realname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.idNumber
     *
     * @mbggenerated
     */
    private String idnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.phoneNumber
     *
     * @mbggenerated
     */
    private String phonenumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.incomeGrade_id
     *
     * @mbggenerated
     */
    private Long incomegradeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.marriage_id
     *
     * @mbggenerated
     */
    private Long marriageId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.kidCount_id
     *
     * @mbggenerated
     */
    private Long kidcountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.educationBackground_id
     *
     * @mbggenerated
     */
    private Long educationbackgroundId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.authScore
     *
     * @mbggenerated
     */
    private Integer authscore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.houseCondition_id
     *
     * @mbggenerated
     */
    private Long houseconditionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.realauthid
     *
     * @mbggenerated
     */
    private Long realauthid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.id
     *
     * @return the value of userinfo.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.id
     *
     * @param id the value for userinfo.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.version
     *
     * @return the value of userinfo.version
     *
     * @mbggenerated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.version
     *
     * @param version the value for userinfo.version
     *
     * @mbggenerated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.bitState
     *
     * @return the value of userinfo.bitState
     *
     * @mbggenerated
     */
    public Long getBitstate() {
        return bitstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.bitState
     *
     * @param bitstate the value for userinfo.bitState
     *
     * @mbggenerated
     */
    public void setBitstate(Long bitstate) {
        this.bitstate = bitstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.realName
     *
     * @return the value of userinfo.realName
     *
     * @mbggenerated
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.realName
     *
     * @param realname the value for userinfo.realName
     *
     * @mbggenerated
     */
    public void setRealname(String realname) {
        this.realname = realname == null ? null : realname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.idNumber
     *
     * @return the value of userinfo.idNumber
     *
     * @mbggenerated
     */
    public String getIdnumber() {
        return idnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.idNumber
     *
     * @param idnumber the value for userinfo.idNumber
     *
     * @mbggenerated
     */
    public void setIdnumber(String idnumber) {
        this.idnumber = idnumber == null ? null : idnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.phoneNumber
     *
     * @return the value of userinfo.phoneNumber
     *
     * @mbggenerated
     */
    public String getPhonenumber() {
        return phonenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.phoneNumber
     *
     * @param phonenumber the value for userinfo.phoneNumber
     *
     * @mbggenerated
     */
    public void setPhonenumber(String phonenumber) {
        this.phonenumber = phonenumber == null ? null : phonenumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.incomeGrade_id
     *
     * @return the value of userinfo.incomeGrade_id
     *
     * @mbggenerated
     */
    public Long getIncomegradeId() {
        return incomegradeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.incomeGrade_id
     *
     * @param incomegradeId the value for userinfo.incomeGrade_id
     *
     * @mbggenerated
     */
    public void setIncomegradeId(Long incomegradeId) {
        this.incomegradeId = incomegradeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.marriage_id
     *
     * @return the value of userinfo.marriage_id
     *
     * @mbggenerated
     */
    public Long getMarriageId() {
        return marriageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.marriage_id
     *
     * @param marriageId the value for userinfo.marriage_id
     *
     * @mbggenerated
     */
    public void setMarriageId(Long marriageId) {
        this.marriageId = marriageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.kidCount_id
     *
     * @return the value of userinfo.kidCount_id
     *
     * @mbggenerated
     */
    public Long getKidcountId() {
        return kidcountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.kidCount_id
     *
     * @param kidcountId the value for userinfo.kidCount_id
     *
     * @mbggenerated
     */
    public void setKidcountId(Long kidcountId) {
        this.kidcountId = kidcountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.educationBackground_id
     *
     * @return the value of userinfo.educationBackground_id
     *
     * @mbggenerated
     */
    public Long getEducationbackgroundId() {
        return educationbackgroundId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.educationBackground_id
     *
     * @param educationbackgroundId the value for userinfo.educationBackground_id
     *
     * @mbggenerated
     */
    public void setEducationbackgroundId(Long educationbackgroundId) {
        this.educationbackgroundId = educationbackgroundId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.authScore
     *
     * @return the value of userinfo.authScore
     *
     * @mbggenerated
     */
    public Integer getAuthscore() {
        return authscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.authScore
     *
     * @param authscore the value for userinfo.authScore
     *
     * @mbggenerated
     */
    public void setAuthscore(Integer authscore) {
        this.authscore = authscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.houseCondition_id
     *
     * @return the value of userinfo.houseCondition_id
     *
     * @mbggenerated
     */
    public Long getHouseconditionId() {
        return houseconditionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.houseCondition_id
     *
     * @param houseconditionId the value for userinfo.houseCondition_id
     *
     * @mbggenerated
     */
    public void setHouseconditionId(Long houseconditionId) {
        this.houseconditionId = houseconditionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.realauthid
     *
     * @return the value of userinfo.realauthid
     *
     * @mbggenerated
     */
    public Long getRealauthid() {
        return realauthid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.realauthid
     *
     * @param realauthid the value for userinfo.realauthid
     *
     * @mbggenerated
     */
    public void setRealauthid(Long realauthid) {
        this.realauthid = realauthid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.email
     *
     * @return the value of userinfo.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.email
     *
     * @param email the value for userinfo.email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }
}